### ISSUE TITLE
sometimes framework can not be found by karma

### ISSUE THREAD

**Issue by mikhail-angelov** [wilsonjackson/karma-angular-filesort#3]
I have error like this:
Warning: No provider for "framework:angular-filesort"! (Resolving: framework:angular-filesort) Use --force to continue.

to solve it, I have to add reference to this package to config plugins

config.set({
...
        plugins: [
            'karma-jasmine',
            'karma-phantomjs-launcher',
            'karma-chrome-launcher',
            'karma-angular-filesort'
        ]
...
}

**Comment by wilsonjackson** [comment]
That happens because specifying a `plugins` property in your karma config overwrites [the default one](https://github.com/karma-runner/karma/blob/master/lib/config.js#L251), which matches all plugins that start with `karma-`. You could omit that part of your karma config and it would function as you expect it to, unless you have installed packages that start with `karma-` that it should specifically not load, which would be unusual.
